title: Yung-Jung Cheng's Personal Academic Website
email: yungjunghotmail@gmail.com
description: Welcome to my personal academic website. Here, I share my research and projects in the field of data science and statistics.
baseurl: ""
url: "https://wdianrdk.github.io"

github_username: wdianrdk
linkedin_username: yung-jung-cheng-8242a913a

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation order
header_pages:
  - index.md
  - About.md
  - contact.md
  - Research.md
  - Projects.md
