title: Yung-Jung Cheng's Personal Academic Website
email: yungjunghotmail@gmail.com
description: Welcome to my personal academic website. Here, I share my research and projects in the field of data science and statistics.
baseurl: ""
url: "https://wdianrdk.github.io"
twitter_username: wdianrdk
github_username:  wdianrdk
linkedin_username: wdianrdk

# Build settings
theme: minima
plugins:
  - jekyll-feed
